<a href="https://colab.research.google.com/github/tanpharamut/data_viz/blob/main/Pandas_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive 
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import os 
path = '/content/drive/My Drive/data_viz'

In [8]:
covid_file_path = os. path.join(path,'pm-20-jan-2021.csv')
print(covid_file_path)

/content/drive/My Drive/data_viz/pm-20-jan-2021.csv

In [7]:
a = path + '/pm-20-jan-2021.csv'
print(a)

/content/drive/My Drive/data_viz/pm-20-jan-2021.csv

##load data to memory

In [11]:
data_covid = pd.read_csv(covid_file_path)
data_covid

         No.  ...                                         risk
0          1  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
1          2  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
2          3  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
3          4  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
4          5  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
...      ...  ...                                          ...
12648  12649  ...                             State Quarantine
12649  12650  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12650  12651  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12651  12652  ...                                Cluster ระยอง
12652  12653  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

[12653 rows x 10 columns]

##แบบง่าย เเต่ใช้การไม่ค่อยได้(มองแบบ array เเล้วตัดแบบ array)

In [12]:
data_covid.iloc[1:5,:]

   No. announce_date  ... district_of_onset                              risk
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[4 rows x 10 columns]

##แบบ advanced เเต่ใช้ประโยชน์ได้เยอะกว่า (ตัดแบบใช้ logic qucy)

In [13]:
data_covid[data_covid['province_of_onset']=='ขอนแก่น']

         No.  ...                                           risk
180      181  ...                                        สนามมวย
462      463  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
1466    1467  ...                  คนไทยเดินทางกลับจากต่างประเทศ
1970    1971  ...  ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว
2637    2638  ...                  สัมผัสผู้เดินทางจากต่างประเทศ
2673    2674  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
5948    5949  ...                              Cluster สมุทรสาคร
6082    6083  ...                              Cluster สมุทรสาคร
9333    9334  ...                           อยู่ระหว่างการสอบสวน
9334    9335  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
10610  10611  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11517  11518  ...                           อยู่ระหว่างการสอบสวน
11697  11698  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11698  11699  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

[14 rows x 10 columns]

### data_covid[x] x สามารถมีค่าที่ใส่เข้าไปได้ 2 แบบ

1. ชื่อ column
2. ใส่ rows ที่ต้องการ (ใส่ list ที่มีขนาดเท่ากับจำนวนเเถว เเล้วบอกว่าเอา แถวไหนบ้างโดย ใช้ logical expression (```True```/```False```)

In [16]:
eight_rows_covid = data_covid.iloc[:8,:]
eight_rows_covid

   No. announce_date  ... district_of_onset                              risk
0    1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
5    6     1/25/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
6    7     1/26/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
7    8     1/26/2020  ...            หัวหิน  คนต่างชาติเดินทางมาจากต่างประเทศ

[8 rows x 10 columns]

In [18]:
eight_rows_covid[[True,False,True,True,False,True,False,False]]

   No. announce_date  ... district_of_onset                              risk
0    1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
5    6     1/25/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[4 rows x 10 columns]

In [22]:
eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร'

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
Name: province_of_onset, dtype: bool

In [23]:
eight_rows_covid[eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร']

   No. announce_date  ... district_of_onset                              risk
0    1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
5    6     1/25/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
6    7     1/26/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
7    8     1/26/2020  ...            หัวหิน  คนต่างชาติเดินทางมาจากต่างประเทศ

[8 rows x 10 columns]

#HW (ให้ใช้เฉพาะที่อาจารย์สอนไปเเล้วในวิชานี้)
#1. คำนวณอายุเฉลยของผู้หญิง เเละผู้ชายของข้อมูลทั้งหมด
#2. คำนวณของผู้หญิง เเละผู้ชายของผู้ป่วยในจังหวัดขอนแก่น

in class หาจำนวนผู้ป่วยที่เป็น คนช่างชาติเดินทางมาจากต่างประเทศ

In [26]:
data_covid[data_covid['risk']=='คนต่างชาติเดินทางมาจากต่างประเทศ']

         No. announce_date  ... district_of_onset                              risk
0          1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1          2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2          3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3          4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4          5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
...      ...           ...  ...               ...                               ...
9852    9853      1/9/2021  ...            แม่สอด  คนต่างชาติเดินทางมาจากต่างประเทศ
10341  10342     1/11/2021  ...            แม่สอด  คนต่างชาติเดินทางมาจากต่างประเทศ
10616  10617     1/12/2021  ...          ปทุุมวัน  คนต่างชาติเดินทางมาจากต่างประเทศ
10619  10620     1/12/2021  ...            บางรัก  คนต่างชาติเดินทางมาจากต่างประเทศ
10620  10621     1/12/2021  ...             วัฒนา  คนต่างชาติเดินทางมาจากต่างประเทศ

[155 rows x 10 columns]

In [28]:
data_covid[data_covid['risk']=='คนต่างชาติเดินทางมาจากต่างประเทศ'].shape[0]

155